### ISSUE TITLE
incompatibility

### ISSUE THREAD

**Issue by tomasabril** [jkoritzinsky/Extensive-Engineer-Report#11]
I installed this mod and the VAB became pretty bugged. I have many mods installed and I suspect there is a incompatibility with one of these. Filter extensions, RCS build aid, StageRecovery.

Windows 8.1 64bit; ksp 1.05 31 bits from steam; mods installed from ckan;
Just letting you know

**Comment by jkoritzinsky** [comment]
Can you export your CKAN mod list? (File > Export installed mods) and attach that here?  Without the modlist I can't figure out what it's breaking/breaking it.

**Comment by tomasabril** [comment]
I renamed it to a txt because github would not allow me to upload a .ckan
As you can see I have a lot of mods installed and i am not currently using your mod. Sorry if this is not too helpful.

[modlist.txt](https://github.com/jkoritzinsky/Extensive-Engineer-Report/files/120511/modlist.txt)

**Comment by jkoritzinsky** [comment]
@tomasabril  When you tried to use Extensive Engineer Report did you also install ShipSections?  I don't see it in your modlist and when you uninstall Extensive Engineer Report it doesn't prompt you to uninstall it.  ShipSections is absolutely required for EER and definitely would bug out the VAB a lot.

**Comment by tomasabril** [comment]
When I had eer installed i also had ship sections. I uninstalled both after the bug. tomorow i will try to install only the mods that might be problematic and try to find the bug again.

**Comment by jkoritzinsky** [comment]
Ok.  I'll take a closer look.  I just wanted to make sure.  Also, can you test just installing ShipSections and seeing if that causes the bad interaction?

**Comment by jkoritzinsky** [comment]
Also, if possible can you send me a game log of the issue (or a craft file that utilizes the mods you have installed)?

**Comment by tomasabril** [comment]
ok, so what I did was copy my game folder and uninstall all the mods. reinstall only 
{
    "kind": "metapackage",
    "abstract": "A list of modules installed on the default KSP instance",
    "name": "installed-default",
    "license": "unknown",
    "version": "2016.02.07.02.20.42",
    "identifier": "installed-default",
    "spec_version": "v1.6",
    "depends": [
        {
            "name": "ShipSections",
            "version": "v1.1"
        },
        {
            "name": "StageRecovery",
            "version": "1.6.2"
        },
        {
            "name": "ExtensiveEngineerReport",
            "version": "v0.5"
        },
        {
            "name": "ModuleManager",
            "version": "2.6.18"
        },
        {
            "name": "FilterExtensions",
            "version": "2.4.1.3"
        },
        {
            "name": "FilterExtensionsDefaultConfig",
            "version": "2.4.1.3"
        },
        {
            "name": "RCSBuildAid",
            "version": "0.7.7"
        }
    ]
}
and then create a new carrer mode and unlock everything with the cheat menu (alt f12).
I didnt see any graphical glitches except for the missing icon. but ship in the vab was unresponsive. I could not select it or add anything or rotate the camera.

When uninstalling eer but leaving ship sections and the others everything works fine.

![captura de tela 2016-02-07 00 27 16](https://cloud.githubusercontent.com/assets/2884097/12870569/0ce5e320-cd32-11e5-8740-0f50f1626b28.png)
![captura de tela 2016-02-07 00 27 36](https://cloud.githubusercontent.com/assets/2884097/12870570/0ce9c1b6-cd32-11e5-8e36-9f0dd0f04cc1.png)
![captura de tela 2016-02-07 00 27 40](https://cloud.githubusercontent.com/assets/2884097/12870571/0ceb6912-cd32-11e5-9685-5bf7805d72ba.png)
![captura de tela 2016-02-07 00 29 02](https://cloud.githubusercontent.com/assets/2884097/12870572/0cef5810-cd32-11e5-90c2-ae3fcd06c4bb.png)

**Comment by jkoritzinsky** [comment]
The underlying issue is with ShipSections, so I'm going to close this here and make a new bug on the ShipSections repo.

**Comment by jkoritzinsky** [comment]
This will be fixed when I do the next ShipSections release.
