### ISSUE TITLE
Extend scientist warning

### ISSUE THREAD

**Issue by rmpalomino** [jkoritzinsky/Extensive-Engineer-Report#3]
Extend the lab with no scientist to "lab with no scientist or reusable experiments with no scientist"

**Comment by jkoritzinsky** [comment]
Reusable experiments don't need a scientist.  You can extract the data on EVA with any type of crew member.  Are you sure you don't mean non-reusable experiments?

**Comment by jkoritzinsky** [comment]
Since I haven't received a response and I implemented the test, I am closing this issue.
