### ISSUE TITLE
Backup battery warning never goes away

### ISSUE THREAD

**Issue by meyerweb** [jkoritzinsky/Extensive-Engineer-Report#5]
After one too many flights where I ignored the backup battery warning to my detriment, I started adding a Z-100 with flow disabled.  However, EER still says the probe lacks a backup.  It persists after adding or subtracting parts, and even shows up on a newly-loaded craft that that has a flow-disabled Z-100.  For example:

![screen shot 2016-01-04 at 15 16 38](https://cloud.githubusercontent.com/assets/939727/12099402/35043d9e-b2f6-11e5-87a7-48033150523d.png)

This is in 1.0.5 modded.  I can provide a list of mods if needed.

**Comment by jkoritzinsky** [comment]
I'm in the process of re-writing all of the EER code for 1.0.5.  I'll check this out with the new version.  Any chance you can post the .craft file that's causing issues?

**Comment by meyerweb** [comment]
Sure, here’s one.  It’s one of the simpler examples I have (and also the craft shown in the previous screenshot).  I’m seeing this behavior on all craft where I’ve tried to add a backup, though.

[Interplanetary Probe Core.craft.txt](https://github.com/jkoritzinsky/Extensive-Engineer-Report/files/77750/Interplanetary.Probe.Core.craft.txt)

**Comment by jkoritzinsky** [comment]
What mods are you using?  I've got Asteroid Day, but I'm still missing some.

**Comment by meyerweb** [comment]
It’s…kind of a list.  I’ve attached CKAN’s output.

[ksp-mods.txt](https://github.com/jkoritzinsky/Extensive-Engineer-Report/files/78054/ksp-mods.txt)

**Comment by jkoritzinsky** [comment]
Ok. I'll take a look when I have a chance.  I've got a few projects all coming to deadlines by end of week so it might take a bit.

**Comment by jkoritzinsky** [comment]
I just tested it out.  It got fixed about a month ago, so I'm closing this issue.

**Comment by meyerweb** [comment]
Oh, that’s embarrassing.  Sorry I missed the fix!

**Comment by jkoritzinsky** [comment]
I missed it too so don't be embarrassed.
