### ISSUE TITLE
1.0.5 compatibility

### ISSUE THREAD

**Issue by linuxgurugamer** [jkoritzinsky/Extensive-Engineer-Report#6]
Is this compatible, if so, can you so indicate and tell CKAN?

**Comment by jkoritzinsky** [comment]
The current version is, but there is a new 1.0.5 update coming out soon.  Soon being when my pull request to update CKAN gets accepted.  You can track it at KSP-CKAN/NetKAN#2914

**Comment by jkoritzinsky** [comment]
@linuxgurugamer I just pushed out the new version, so take a look at it!

**Comment by linuxgurugamer** [comment]
Ok, thanks
