### ISSUE TITLE
White icon in VAB

### ISSUE THREAD

**Issue by linuxgurugamer** [jkoritzinsky/Extensive-Engineer-Report#7]
The VAB icon is white, looks like either a missing or misplaced icon
I should note that this is on Linux, which means that it is case sensitive (ie:  "icon" != "Icon" )
I checked in Windows, still white.  This was a totally clean install

**Comment by jkoritzinsky** [comment]
So this didn't actually get fixed.  I'll keep working on it.

**Comment by jkoritzinsky** [comment]
Apparently `GameDatabase` doesn't like spaces in files, but because of NetKAN I can't fully change it without breaking a CKAN release.  I'm trying to decide how I'm going to do this.

**Comment by jkoritzinsky** [comment]
I'm going to break the NetKAN metadata and then send a PR to fix it.
