### ISSUE TITLE
Adding scientist to lab not acknowledged

### ISSUE THREAD

**Issue by linuxgurugamer** [jkoritzinsky/Extensive-Engineer-Report#9]
I was setting up a launch, and one of the warnings I got was no scientist the lab.  so I added a few, but it didn't clear the warning until I clicked on the red radio button for it, then it saw and recognized their prescence

**Comment by linuxgurugamer** [comment]
Update:  I loaded a mobile processing lab, and saw the science lab warning.  I then loaded a scientist, warning stayed until I clicked back on the Parts icon

**Comment by jkoritzinsky** [comment]
The behavior in your update matches the original Engineer's Report.  I'll look at changing it to update while on the crew tab.

**Comment by jkoritzinsky** [comment]
For my reference, here's a link for someone else who needed the same thing: http://forum.kerbalspaceprogram.com/index.php?/topic/126597-how-to-track-crew-assignments-in-editor-~answered~/#comment-2300393
